<?php

/**
 * @file
 * Contains content_profile_export.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function content_profile_export_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the content_profile_export module.
    case 'help.page.content_profile_export':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('This module is used to copy all the fields from the User Profile Enabled Content Type in Drupal 6 to Drupal 8 User Profile') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function content_profile_export_theme() {
  return [
    'content_profile_export' => [
      'render element' => 'children',
    ],
  ];
}
